README.md
index.js

Squidniiii-updated-thirst-command

---

index.js

Should be useful for stopping spam messages.

Deny 'quote' command in #general

---

README.md
index.js
test.js

Fix spacing and style

---

README.md
index.js
package-lock.json
package.json

I've got a command working that allows someone to type, say "queen class CS-125", and get back the full name, credit hours, avg. GPA, and description!
The code isn't as clean as I'd like it, and currently I've left some console.log() commands that can be a bit spammy, since I was testing it. I plan to clean those up later today, but I figured I'd still submit the pull request now.
Also, when the bot initially starts, it will need to load the CSV data for the first time. It doesn't take very long, only about ~1 minute, and then the bot is ready to go.

*Working* Class Command

---

README.md
index.js

- Added a waitwhen command that shows a wait when screenshot
- Updated README.md accordingly

Add waitwhen command

---

README.md
index.js

QUEEN MOON BOT WILL SAY I AM BUFF

buff nooble buff nooble

---

index.js

Still using the same image, just a better crop (less whitespace)

Crop "wait, when?" image better

---

index.js

fix queen matt

---

README.md
index.js

- added a super sick corn command

Added corn command

---

index.js

Shouldnt we use Math.round(bot.ws.ping) instead because of how its more consistent, cause when I tried it I consistently got the same ping instead of variation.

Fixing Ping Variance

---

index.js

Bot functionality is not needed in this channel.

Deny all commands in #general

---

index.js

Sometimes you have to be faster.

Add 'ww' as an alias for waitwhen

---

index.js

it did not format the tabs right so Please leave it for hassan to do it, i beg you

Fixing crappy help command for HaSsAn

---

index.js

Fulfilling a request from the Discord

---

util/commands.js

Sorry command

---

README.md
util/commands.js

Added command 'q tvd' to get a picture of a dancing cockroach.

adding q tvd

---

index.js

read to make sure I didnt mess it up

pronoun reacts

---

util/commands.js

Remove unused command

---

util/commands.js

Limit usage of quote command

---

README.md
index.js
util/commands.js

Not really a super useful command, but kinda fun. Takes advantage of the newly added long cat emojis to create cats of any length specified. The :catfeet: and :cathead: emojis will be used no matter what, but the length parameter will add up to 30 :catbod: emojis. If more than 30 are requested, Alma Botter will say "too looong."

'otter cat [length]' command

---

util/commands.js

add q korn to add man in cornrows eats corn while listening to korn

add q korn
